(function($) {
    $(document).ready(function() {
	
	$('#gd_convexa').scianimator({
	    'images': ['animaciones/Gradiente Descendente/images//gd_convexa1.png', 'animaciones/Gradiente Descendente/images//gd_convexa2.png', 'animaciones/Gradiente Descendente/images//gd_convexa3.png', 'animaciones/Gradiente Descendente/images//gd_convexa4.png', 'animaciones/Gradiente Descendente/images//gd_convexa5.png', 'animaciones/Gradiente Descendente/images//gd_convexa6.png', 'animaciones/Gradiente Descendente/images//gd_convexa7.png', 'animaciones/Gradiente Descendente/images//gd_convexa8.png', 'animaciones/Gradiente Descendente/images//gd_convexa9.png', 'animaciones/Gradiente Descendente/images//gd_convexa10.png', 'animaciones/Gradiente Descendente/images//gd_convexa11.png', 'animaciones/Gradiente Descendente/images//gd_convexa12.png', 'animaciones/Gradiente Descendente/images//gd_convexa13.png', 'animaciones/Gradiente Descendente/images//gd_convexa14.png', 'animaciones/Gradiente Descendente/images//gd_convexa15.png', 'animaciones/Gradiente Descendente/images//gd_convexa16.png', 'animaciones/Gradiente Descendente/images//gd_convexa17.png', 'animaciones/Gradiente Descendente/images//gd_convexa18.png', 'animaciones/Gradiente Descendente/images//gd_convexa19.png', 'animaciones/Gradiente Descendente/images//gd_convexa20.png', 'animaciones/Gradiente Descendente/images//gd_convexa21.png', 'animaciones/Gradiente Descendente/images//gd_convexa22.png', 'animaciones/Gradiente Descendente/images//gd_convexa23.png', 'animaciones/Gradiente Descendente/images//gd_convexa24.png', 'animaciones/Gradiente Descendente/images//gd_convexa25.png', 'animaciones/Gradiente Descendente/images//gd_convexa26.png', 'animaciones/Gradiente Descendente/images//gd_convexa27.png', 'animaciones/Gradiente Descendente/images//gd_convexa28.png', 'animaciones/Gradiente Descendente/images//gd_convexa29.png', 'animaciones/Gradiente Descendente/images//gd_convexa30.png', 'animaciones/Gradiente Descendente/images//gd_convexa31.png', 'animaciones/Gradiente Descendente/images//gd_convexa32.png', 'animaciones/Gradiente Descendente/images//gd_convexa33.png', 'animaciones/Gradiente Descendente/images//gd_convexa34.png', 'animaciones/Gradiente Descendente/images//gd_convexa35.png', 'animaciones/Gradiente Descendente/images//gd_convexa36.png', 'animaciones/Gradiente Descendente/images//gd_convexa37.png', 'animaciones/Gradiente Descendente/images//gd_convexa38.png', 'animaciones/Gradiente Descendente/images//gd_convexa39.png', 'animaciones/Gradiente Descendente/images//gd_convexa40.png', 'animaciones/Gradiente Descendente/images//gd_convexa41.png', 'animaciones/Gradiente Descendente/images//gd_convexa42.png', 'animaciones/Gradiente Descendente/images//gd_convexa43.png', 'animaciones/Gradiente Descendente/images//gd_convexa44.png', 'animaciones/Gradiente Descendente/images//gd_convexa45.png', 'animaciones/Gradiente Descendente/images//gd_convexa46.png', 'animaciones/Gradiente Descendente/images//gd_convexa47.png', 'animaciones/Gradiente Descendente/images//gd_convexa48.png'],
	    'width': 480,
	    'delay': 1000,
	    'loopMode': 'loop'
	});
	$('#gd_convexa').scianimator('play');
    });
})(jQuery);
