(function($) {
    $(document).ready(function() {
	
	$('#gd_dos_minimos1').scianimator({
	    'images': ['animaciones/Gradiente Descendente/images//gd_dos_minimos11.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos12.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos13.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos14.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos15.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos16.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos17.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos18.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos19.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos110.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos111.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos112.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos113.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos114.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos115.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos116.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos117.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos118.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos119.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos120.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos121.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos122.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos123.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos124.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos125.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos126.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos127.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos128.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos129.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos130.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos131.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos132.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos133.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos134.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos135.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos136.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos137.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos138.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos139.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos140.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos141.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos142.png', 'animaciones/Gradiente Descendente/images//gd_dos_minimos143.png'],
	    'width': 480,
	    'delay': 1000,
	    'loopMode': 'loop'
	});
	$('#gd_dos_minimos1').scianimator('play');
    });
})(jQuery);
