(function($) {
    $(document).ready(function() {
	
	$('#gd_dos_minimos2').scianimator({
	    'images': ['animaciones/Gradiente Descendente/images/gd_dos_minimos21.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos22.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos23.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos24.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos25.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos26.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos27.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos28.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos29.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos210.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos211.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos212.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos213.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos214.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos215.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos216.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos217.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos218.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos219.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos220.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos221.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos222.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos223.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos224.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos225.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos226.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos227.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos228.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos229.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos230.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos231.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos232.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos233.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos234.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos235.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos236.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos237.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos238.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos239.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos240.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos241.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos242.png', 'animaciones/Gradiente Descendente/images/gd_dos_minimos243.png'],
	    'width': 480,
	    'delay': 1000,
	    'loopMode': 'loop'
	});
	$('#gd_dos_minimos2').scianimator('play');
    });
})(jQuery);
